### ISSUE TITLE
Publish 0.7.2 release?

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#106]
#81, #85, #94, #95, #104 done.
Is there anything else we want to implement in 0.7.2?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov I think it's enough for new release :+1: , please test it and prepare release draft, I'll publish it to the Google Play Store

**Comment by ilya-murzinov** [comment]
Tested, see #111.
[Release draft](https://github.com/artem-zinnatullin/android-wail-app/releases)

We are good to go!

**Comment by artem-zinnatullin** [comment]
Okay, publishing

**Comment by artem-zinnatullin** [comment]
Done!
