### ISSUE TITLE
German Play Store Description

### ISSUE THREAD

**Issue by tehabe** [artem-zinnatullin/android-wail-app#113]
The current German Play Store description makes no sense.

My translation would be: "Einfach zu benutzender Last.fm-Scrobbler. Auch für Tablets geeignet."

![2015-02-03 13 02 47](https://cloud.githubusercontent.com/assets/3908663/6021567/156c45c2-abb7-11e4-9a3b-f94c84ce4a5d.png)

**Comment by artem-zinnatullin** [comment]
@tehabe can you please provide translation for all fields for app description, I can't translate only one part and leave others in English…

Short description: "Nice last.fm scrobbler with great ui optimized for tablets! You'll love it".

Full description: "Nice & simple last.fm scrobbler with Material Design for your android! It captures music playing events from your favorite music players and then scrobbles tracks to the last.fm.

Nowplaying for last.fm supported!

WAIL Beta is now Open Source: check out https://github.com/artem-zinnatullin/android-wail-app
WAIL supports a lot of music players, give it a try! :)"

At the moment, Google Play automatically translates description via Google Translator.

**Comment by tehabe** [comment]
So, here my first draft.

Short Description: "Einfach zu benutzender Last.fm-Scrobbler. Auch für Tablets geeignet."

Full description: "WAIL ist ein einfacher last.fm-Scrobbler für Android. Es erfasst die gespielten Titel von vielen beliebten Musikapps und scrobbelt diese zu last.fm

Mit Nowplaying kann auf last.fm der aktuelle Titel angezeigt und geteilt werden.

WAIL ist Open Source. Auf https://github.com/artem-zinnatullin/android-wail-app findest Du den Quellcode und mehr."

**Comment by artem-zinnatullin** [comment]
Thanks, I'll use them today!
8 июня 2015 г. 11:55 AM пользователь "Thomas Bohn" <notifications@github.com>
написал:

**Comment by artem-zinnatullin** [comment]
Done, thanks a lot!
