### ISSUE TITLE
Bug with the definition of the name of the player Neutron

### ISSUE THREAD

**Issue by raxemus** [artem-zinnatullin/android-wail-app#121]
WAIL displays it as com.android.music
http://4pda.ru/forum/index.php?showtopic=248705

**Comment by ilya-murzinov** [comment]
Hi, @raxemus
It's not a bug, Neutron just sends it's intents with package name com.android.music.
There is nothing we can do.

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov #8 :dancer:
