### ISSUE TITLE
Suggested improvement to German localization

### ISSUE THREAD

**Issue by kasoban** [artem-zinnatullin/android-wail-app#126]
The current values-de/strings.xml lists the following translation:

`<string name="drawer_registered_at">"Registrierte "</string>`

A sample output of the usage in the menu drawer:
"Registrierte 2008-05-03"

Instead I would suggest either "Registriert seit" or "Registriert am".
@tehabe since you wrote the original set, what is your opinion on this?

**Comment by tehabe** [comment]
I agree, I would change it to "Mitglied seit". Will add an push request soon.
