### ISSUE TITLE
Spotify not detected

### ISSUE THREAD

**Issue by marszczybrew** [artem-zinnatullin/android-wail-app#129]
I have Android 5.0 on LG G3 and, as mentioned above, this app doesn't detect music played on Spotify, whereas it does if I play from the default player. I have Spotify Premium and run the latest version of it.

**Comment by artem-zinnatullin** [comment]
Hello @marszczybrew, it's problem of current playing music info recognition mechanism, it can be solved by #8 

But both of developers: @ilya-murzinov and me are too busy :disappointed: 

If you can help -> Pull Requests are highly appreciated!
