### ISSUE TITLE
Scrobbing configuration

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#131]
From email: "I mostly listen to Indian soundtracks which generally has one composer for the whole movie and different artists singing each track. With the existing scrobbling of "Song Artist - Track name" is kinda misleading for Indian soundtracks. I would love to have an user option which would let me scrobble "Album Artist - Track name". "

**Comment by angmyu** [comment]
I also want that option: https://github.com/artem-zinnatullin/android-wail-app/issues/100

**Comment by ilya-murzinov** [comment]
Duplicate #100
