### ISSUE TITLE
Bugs bugs bugs

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#135]
From email:

Firstly, I like to do some tests when I get a new scrobbler:
1) Play track and pause it several times to ensure it does not scrobble the track several times - OK
2) Play track on repeat (2x) so it is correctly scrobbled
3) Play track again, but hit restart before the track is finished (over 50% of the track)

I did the 3 tests, but I only got 2 scrobbles on my account. The WAIL app showed 4 songs, but in the end I did not get them all. The difference is 5 minutes between them, so I guess the test 3 did not work.
Then, I tried to scrobble more tracks, but it showed the artist name next to "null", so in the end it did not scrobble.

**Comment by ilya-murzinov** [comment]
I think, this is related to #26 and should be retested after it fixed.
But it can be also related to some network issues.

**Comment by ilya-murzinov** [comment]
Ok, I retested this.
 1. Passes if one of intervals between pauses is longer than 50% of tracks duration. I think it's the correct behavior.
 1. Passes.
 1. Passes.

Thanks to whoever reported this :+1

**Comment by lemerafael** [comment]
It was me! I'm glad I could help and you could fix it!
