### ISSUE TITLE
Saving battery by using latest Project Volta-APIs (aka job-scheduling)

### ISSUE THREAD

**Issue by dotWee** [artem-zinnatullin/android-wail-app#137]
How about implementing a job-scheduler [(reference)](https://developer.android.com/about/versions/android-5.0.html#Power) for the scrobbling-task? 
A problem could be the actual API, since it's only available for APIs greater than 21.

**Comment by ilya-murzinov** [comment]
I don't think it worth effort.
@artem-zinnatullin do you?
