### ISSUE TITLE
Fix Lint warnings

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#147]
This is the issue to start with for new developers I believe.
Just run ```./gradlew check``` and you'll see warnings in ```/android-wail-app/wail-app/build/outputs/lint-results.html```.
Not all of them are relevant, but lots of them are.

**Comment by artem-zinnatullin** [comment]
+1, would be nice to fix them all!

**Comment by joonki34** [comment]
I am currently working on this and have a question. Would it be ok to remove unused resources, especially in strings.xml? I believe translators wouldn't want to spend their time on translating unused strings.

**Comment by artem-zinnatullin** [comment]
If they are really not used — delete them :)

Anyway we'll review PR.

**Comment by ilya-murzinov** [comment]
Fixed by #152
