### ISSUE TITLE
Scrobbling track without any indication.

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#148]
From e-mail:
>when playing a podcast  in Pocket Casts, the Wail App doesn't show an app currently being scrobbled, but the Last.fm website shows "Scrobbling from: WAIL Beta (Android scrobbler)"

>Since Pocket Casts doesn't show in the "Now scrobbling" area, I can't ignore it.  My list of ignored players is empty.

**Comment by ilya-murzinov** [comment]
Possible workaround is to allow user to add arbitrary application to the list of ignored, but we need to find the root cause.

**Comment by artem-zinnatullin** [comment]
JFYI: as far as I remember — Pocket Casts sends intents as "com.android.music"

**Comment by ilya-murzinov** [comment]
Yep, and also it always sends "playing == false", and it the problem :(

**Comment by ilya-murzinov** [comment]
Nothing we can do here.
