### ISSUE TITLE
Enable browser based last.fm authentication.

### ISSUE THREAD

**Issue by nasa42** [artem-zinnatullin/android-wail-app#15]
Some users are too paranoid (me?) to enter their last.fm credentials in a third-party app. It would be great if WAIL allows users to authorise WAIL to access their last.fm account using browser authentication.
More information here: http://www.last.fm/api/desktopauth

**Comment by ilya-murzinov** [comment]
Will work on this.

**Comment by nasa42** [comment]
Many thanks @ilya-murzinov. :-)

**Comment by artem-zinnatullin** [comment]
:+1:
