### ISSUE TITLE
WAIL crashes after some time without usage.

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#162]
@joonki34:
>I am not sure it's just my phone but sometimes WAIL gets crashed when I relaunch the app after a long period of time (at least more than several hours) from the first run. I can't identify what's causing it. Does WAIL store crash log somewhere (maybe in GA)?

**Comment by joonki34** [comment]
Got it! It was NullPointerException and it occurs [here] (https://github.com/artem-zinnatullin/android-wail-app/blob/25105ad0c60d8902eeb1d9dc7b6746aa22497b81/wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/MainFragment.java#L150).

**Comment by ilya-murzinov** [comment]
@joonki34, good job! Many thanks!

**Comment by ilya-murzinov** [comment]
OH SHI~
Seems that #132, #133, #134 are about this too.
My bad :(

**Comment by ilya-murzinov** [comment]
@joonki34, please retest this, I can't reproduce it anywhere. Thanks.

**Comment by joonki34** [comment]
@ilya-murzinov Well, I did the same experiment and now it doesn't crash. I think it's safe to say that the issue is fixed.

**Comment by ilya-murzinov** [comment]
@joonki34, ok, thanks you!
