### ISSUE TITLE
Reintroduce "Ignore player" functionality

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#170]
"Ignore player" functionality apparently was a "killer-feature" (at least for one user).
So we need to find a way to bring it back.

**Comment by somegirl** [comment]
Like the other user, I am holding off on updating due to not being able to ignore Rdio, so I hope this feature can be added back.

**Comment by ilya-murzinov** [comment]
Closed via #171
