### ISSUE TITLE
V0.7.3 stopped scrobbling

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#173]
There are couple of reviews on Google Play about WAIL not working after update.

**Comment by ilya-murzinov** [comment]
Have anybody here experienced the same issue?

**Comment by bassstorm** [comment]
Works like a charm for me (Xperia Z3, Android 5.0.2).

**Comment by ilya-murzinov** [comment]
Yep, for me too.
Although there are some changes that could affect others.
But I can't do pretty much anything without any information :(

**Comment by artem-zinnatullin** [comment]
I'll ask them in Google Play.
3 июля 2015 г. 6:46 PM пользователь "Ilya Murzinov" <
notifications@github.com> написал:

**Comment by ilya-murzinov** [comment]
There is also review saying "After update one song scrobbling 10 times".
I suppose, this issues have something to do with #146

**Comment by ilya-murzinov** [comment]
I managed to reproduce it, will fix.

**Comment by ilya-murzinov** [comment]
Ok, done with "not scrobbling" problem.
But "one song scrobbling 10 times" is not clear.
@artem-zinnatullin, please ask Aaki Nagdev on Google Play what player he is using.

**Comment by artem-zinnatullin** [comment]
Done, asked him to write us via email

On Sat, Jul 4, 2015 at 2:45 PM, Ilya Murzinov <notifications@github.com>
wrote:

> Ok, done with "not scrobbling" problem.
> But "one song scrobbling 10 times" is not clear.
> @artem-zinnatullin <https://github.com/artem-zinnatullin>, please ask
> Aaki Nagdev on Google Play what player he is using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/android-wail-app/issues/173#issuecomment-118494303>
> .
>



-- 
------------------
Best regards, Artem Zinnatullin
Sent from my bed.

**Comment by ilya-murzinov** [comment]
Let's reopen this if Aaki Nagdev replies.
