### ISSUE TITLE
Scrobbling error after 0.7.3 and 0.7.4 update.

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#177]
I think #163 could have affected this.
@artem-zinnatullin, @regisd please take a look. 
![screenshot_2015-07-05-21-43-03](https://cloud.githubusercontent.com/assets/3704363/8558881/492bf204-2510-11e5-99b6-690436b8fa1c.png)
![screenshot_2015-07-05-21-42-49](https://cloud.githubusercontent.com/assets/3704363/8558878/42066914-2510-11e5-9717-b0e79448f662.png)

**Comment by lemerafael** [comment]
I noticed the same thing, I came here also to report the issue...

**Comment by ilya-murzinov** [comment]
@lemerafael, can you please share your logcat?

**Comment by regisd** [comment]
The same MD5 is used for the OAuth process which still works. I'm having a look.

**Comment by regisd** [comment]
I cannot reproduce with Google Play Music.
@lemerafael What player are you using?

**Comment by regisd** [comment]
Is it a duplicate of issue #173 ?

**Comment by lemerafael** [comment]
Sure, could you give me some instructions on how to do that? (I am a begginer)
Mainly, I am using Rocket Player, but I also use Play Music and Samsung Music Player sometimes. I realised when I used the Samsung Player, I got null on the first song and then the scrobble failed on all the other ones.

**Comment by bassstorm** [comment]
Same here. See some issues from time time (double scrobbles or a missing track - PowerAmp player) but unable to analyze. Installed aLogcat and Catlog today, but there's nothing related to WAIL there. Perhaps, it requires root?

**Comment by ilya-murzinov** [comment]
Hi guys,
@regisd, this is not duplicate of #173. Those issue is about tracks not scrobbled by WAIL itself, this one is about WAIL being unable to send scrobbled tracks to LastFM.
@lemerafael, @bassstorm, please see [this](http://forum.xda-developers.com/showthread.php?t=1726238) article.
We are not looking for an exception in the log, we need to see something like "WAILService all tracks marked as scrobbled, skipping scrobble", "WAILService tracks scrobbling to Last.fm failed with network error"  or "WAILService tracks scrobbling to Last.fm failed with api error:"

**Comment by lemerafael** [comment]
The failures from my logcat are:

07-13 19:27:50.882 E/WAIL    (25188): WAILService tracks scrobbling to Last.fm failed with api error: Missing required parameter track[2]

07-13 19:28:00.292 W/PackageManager(28602): Failure retrieving resources for com.artemzin.android.wail: Resource ID #0x0

I would attach the full file here, but it looks like I can't. Would you have any alternate suggestion for uploading the full file? Do you need it anyway?

**Comment by ilya-murzinov** [comment]
@lemerafael, yes, please send it to my [e-mail](mailto:murz42@gmail.com)

**Comment by ilya-murzinov** [comment]
From e-mail:
> You can see in the screenshot that scrobbling hangs after it reads a song that has no description.
Thought you'd wanna know.
Thanks for the app.

![screenshot_2015-07-14-02-28-45](https://cloud.githubusercontent.com/assets/3704363/8671755/7b2d45e4-2a30-11e5-8edc-f9c007cafc0d.png)

**Comment by ilya-murzinov** [comment]
Ok, I's starting to understand the problem. 
Seems that after WAIL captured a track with no data it can't scrobble anymore.

**Comment by ilya-murzinov** [comment]
The solution is pretty obvious - we should not just add track without correct information to DB for scrobbling.
@artem-zinnatullin, please verify.

**Comment by artem-zinnatullin** [comment]
Oh, that's bad.
14 июля 2015 г. 2:00 PM пользователь "Ilya Murzinov" <
notifications@github.com> написал:

**Comment by ilya-murzinov** [comment]
Only one thing I can't understand - why did this came up in 0.7.3, not earlier?

**Comment by artem-zinnatullin** [comment]
I guess some logic of working with API was changed and it prevents sending
request for scrobbling if one track can not be scrobbled.

BTW we don't only need to prevent saving tracks with incorrect info into
the db, we also should delete them on app update otherwise it'll help only
for new users/reinstalls.
14 июля 2015 г. 2:04 PM пользователь "Ilya Murzinov" <
notifications@github.com> написал:

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, yes, you are right.
I will submit the solution ASAP.

**Comment by ilya-murzinov** [comment]
Fixed in #186, thanks, guys!
