### ISSUE TITLE
Remove support for custom language

### ISSUE THREAD

**Issue by regisd** [artem-zinnatullin/android-wail-app#183]
Currently, WAIL supports a setting whereby the user can choose a different language.

Locales are already natively handled by the platform. I don't think the setting that let the user choose a different language makes sense.

Removing this feature:

* Is consistent with how virtually all apps behave
* will simplify the settings, hence making a simpler better app
* will remove code, hence making the code smaller and easier
* may simplify the implementation of RTL #182

**Comment by artem-zinnatullin** [comment]
No, please, I usually use English system but I live in Russia, and I prefer to use some (not all but a few) apps in Russian, so these feature makes sence at least for me, but it's not so critical.

Also, it makes testing of different languages easier because it does not require changing system language.

@ilya-murzinov thoughts?

**Comment by joonki34** [comment]
I also use English settings although I live in Korea. Adding 'device language' option as default like Facebook app would be helpful.

**Comment by regisd** [comment]
The default language is already "Auto", which is the locale of the device.

**Comment by ilya-murzinov** [comment]
I would agree with @regisd.
As a developer, I'd like to remove as much as possible.
As a user, I always use English locale anyway.

I think we can remove it and see how people react.

**Comment by artem-zinnatullin** [comment]
I guess we'll receive only negative feedback, because most of users even
don't know that they can change language in tg the app, but little part
that use it will be angry.
14 июля 2015 г. 8:58 PM пользователь "Ilya Murzinov" <
notifications@github.com> написал:

**Comment by ilya-murzinov** [comment]
Yes, I worry about this too.

**Comment by artem-zinnatullin** [comment]
So, I am closing this for now, feel free to reopen/comment.
