### ISSUE TITLE
Rename 'develop' to 'master'

### ISSUE THREAD

**Issue by regisd** [artem-zinnatullin/android-wail-app#187]
Please follow the git convention and rename 'develop' to 'master'.

**Comment by artem-zinnatullin** [comment]
JFYI: I am not a fan of standard Git Flow for about 1.5 years, here is article that shares same opinions as mine, take a look :) http://endoflineblog.com/gitflow-considered-harmful

+1 for renaming `develop` to `master` and simplifying our Git Flow into one branch with tags and feature/fix branches for PRs ((with squashing into one commit before merge).

@ilya-murzinov what do you think?

**Comment by ilya-murzinov** [comment]
Sure, ```master``` branch is currently useless.

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov can you please do it and leave one main branch in the repo?

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, I think I don't have enough rights to do this.

```
$ git push upstream --delete develop
Username for 'https://github.com': ilya-murzinov
Password for 'https://ilya-murzinov@github.com':
remote: error: refusing to delete the current branch: refs/heads/develop
To https://github.com/artem-zinnatullin/android-wail-app
 ! [remote rejected] develop (deletion of the current branch prohibited)
error: failed to push some refs to 'https://github.com/artem-zinnatullin/android
-wail-app'
```

**Comment by artem-zinnatullin** [comment]
Nope, problem is that develop is currently default branch in GitHub repo
settings, just change it to master.

BTW, please don't forget to merge develop into master before dropping
develop branch.

On Wed, Jul 15, 2015 at 7:37 PM, Ilya Murzinov <notifications@github.com>
wrote:

> @artem-zinnatullin <https://github.com/artem-zinnatullin>, I think I
> don't have enough rights to do this.
>
> $ git push upstream --delete develop
> Username for 'https://github.com': ilya-murzinov
> Password for 'https://ilya-murzinov@github.com':
> remote: error: refusing to delete the current branch: refs/heads/develop
> To https://github.com/artem-zinnatullin/android-wail-app
>  ! [remote rejected] develop (deletion of the current branch prohibited)
> error: failed to push some refs to 'https://github.com/artem-zinnatullin/android
> -wail-app <https://github.com/artem-zinnatullin/android-wail-app>'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/android-wail-app/issues/187#issuecomment-121672267>
> .
>



-- 
------------------
Best regards, Artem Zinnatullin
Sent from my bed.

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, yep, I know that I can't delete default branch, but I can't change it because I don't have rights :)

**Comment by artem-zinnatullin** [comment]
Oh, okay, changed to master!

**Comment by ilya-murzinov** [comment]
Done!
