### ISSUE TITLE
Change versioning rules

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#190]
I think, we should follow [Semantic versioning](http://semver.org/).
Since we are in "beta" stage, I think we should increase minor version (i.e. 0.7.0 -> 0.8.0) when we introduce new features and increase patch version (i.e. 0.7.0 -> 0.7.1) when we just release some bug-fix.
@artem-zinnatullin, do you agree?

**Comment by artem-zinnatullin** [comment]
Mm, it depends on our purposes :)

If we will use Semantic Versioning we will have version 40+ (like Chrome) pretty fast.

But why not :)

**Comment by artem-zinnatullin** [comment]
So, let's just do it, I am closing this for now :)

**Comment by ilya-murzinov** [comment]
Ok!
