### ISSUE TITLE
Tracks scrobbling multiple times

### ISSUE THREAD

**Issue by gonemad** [artem-zinnatullin/android-wail-app#198]
This seems to be happening quite often to me.  When i go to last.fm i'll see sometimes 2-4 scrobbles of the same track, all at the exact same time.  When I go into Wail and look at what is being scrobbled, it only shows up once.  Is it possible wail thinks its failing and is retrying again.. so it sends a bunch of scrobbles at once?

**Comment by NAUSHNIK52** [comment]
It is Last.FM issue, not WAIL.

**Comment by gonemad** [comment]
why is it only happening with WAIL then?  I dont seem to have the issue when i scrobble from musicbee, nor did i have issues in the past with simple last.fm scrobbler

**Comment by NAUSHNIK52** [comment]
I don't know, but I have this issue with WAIL, Chrome Web Scrobbler and I read that some users experiencing this issue too (official Last.fm forums, Reddit).

**Comment by gonemad** [comment]
yeah.. nevermind.. you are right.  I wasnt experiencing it before with other scrobbling methods.. but just looked now and its repeating for musicbee as well.  This can be closed
