### ISSUE TITLE
Scrobble error

### ISSUE THREAD

**Issue by effupthefun** [artem-zinnatullin/android-wail-app#200]
I'm getting a "scrobble error" after last.fm forced us to use the new layout. It's been like this for 2 (or 3?) days

**Comment by artem-zinnatullin** [comment]
Helo!

Looks like Last.fm has some internal problems (and changes!), you can check their twitter: https://twitter.com/lastfm

We will monitor this, I hope they'll just make things work again and WAIL will scrobble your tracks (even those, that were not sent because of this problem).
