### ISSUE TITLE
After Last.fm website update Scrobbling issue

### ISSUE THREAD

**Issue by keyursakaria** [artem-zinnatullin/android-wail-app#201]
Hey there,

After the new last fm website update the application is unable to scrobble either its scrobbling... or scrobble error. I logged out and sign in again it worked for a while and then again it stopped scrobbling.

**Comment by nIELSEn74** [comment]
same for me, the best of all scrobblers stopped scrobbling - but after logging out i can't even log in to last.fm any more via wail

**Comment by ilya-murzinov** [comment]
@nIELSEn74 what kind of error do you get?

**Comment by nIELSEn74** [comment]
hello ilya,

in the meantime it's possible to login,  but the connection between wail
and last.fm still fails
Am 23.08.2015 20:32 schrieb "Ilya Murzinov" <notifications@github.com>:

**Comment by Mastinal** [comment]
I'm also having this issue.

I receive a "Last.fm error: Value <?xml of type java.lang.String cannot be converted to JSONObject" message when I try to refresh the app.

**Comment by nIELSEn74** [comment]
now that the wail-app got connected to last.fm it can't scrobble anyway :(
Am 23.08.2015 20:32 schrieb "Ilya Murzinov" <notifications@github.com>:

**Comment by kasoban** [comment]
> I receive a "Last.fm error: Value <?xml of type java.lang.String cannot be converted to JSONObject" message when I try to refresh the app.

Can confirm this behavior with wail 0.7.5 beta, it only happens through the "refresh"/"update" action on the dashboard view though.

Scrobbling still works fine for me.
