### ISSUE TITLE
Goodbye.

### ISSUE THREAD

**Issue by insintesi** [artem-zinnatullin/android-wail-app#214]
Just wanted to say I'm very grateful for your work and am sad to see that development has come to an end. It still works by and large, but I notice certain smaller things that used to make WAIL special don’t work anymore (e.g. scrobbling Deezer when broadcast via Chromecast). What a bummer.

**Comment by artem-zinnatullin** [comment]
Yeah, since there is no "standard" way to get informations from players on all Android versions some apps may not work after updates.

Sorry for end of development, I just have no time and motivation to work on it.
