### ISSUE TITLE
Multiple track scrobbling

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#26]
There is a bug (incorrect behavior) in WAIL.

WAIL can scrobble track multiple times if you or Android will pause the track WAIL can scrobble it, and then, scrobble it again if it will be continued

**Comment by vladislav-lozovskiy** [comment]
Very unpleasant bug. As a workaround I set "Min track elapsed in seconds"  = 240. In most cases it helps

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, @vladislav-lozovskiy how should we detect that track continues playing but not played again?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov best solution -> switch to another mechanism of getting music playing info, see #8, and may be it's possible to create full music playing state machine which will be able to say that track was paused, then resumed and so on

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin I think we should remove "Min track time elapsed in seconds", it automatically will solve this. Any thoughts?

**Comment by ilya-murzinov** [comment]
And by the way, I discovered that some players set duration in seconds, not milliseconds. This can cause this bug again.

**Comment by artem-zinnatullin** [comment]
Shit, I think it's better to implement #8 which should resolve this issue..

вт, 3 февр. 2015, 1:02, Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin I don't see how #8 can help. Actually, I'm implementing it right now and the FIRST thing that I noticed was that WAIL started to scrobble all tracks, regardless how long they were played.

Actually, I think that this bug is caused by some players setting duration in seconds, not milliseconds.

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin we can keep "Min track time elapsed in seconds", but the checking MUST be implemented like this:
```java
if (trackPlayingDurationInMillis >= minTrackDurationInMillis) {
    if (mLastCapturedTrackInfo.getTrack().getDuration() != -1) {
        if (trackDurationInPercents >= minTrackDurationInPercents) {
            //SCROBBLING
        } else {
            //NOT SCROBBLING
        }
    } else {
        //SCROBBLING
    }
}
```

And this bug will be resolved.
I Insist on this solution.
Thoughts?

**Comment by artem-zinnatullin** [comment]
LGTM

**Comment by bassstorm** [comment]
Can't wait for this fix, really annoying issue.

**Comment by ilya-murzinov** [comment]
@bassstorm, just wait for 0.7.3 release (#159). Hope, @artem-zinnatullin will publish it soon!

**Comment by lemerafael** [comment]
It seems the app is not respecting the duration of 50% or maybe is it the same time bug that was reported here? I am getting multiple scrobbles when I pause a track and then I restart it: I get a scrobble before and then I get a new scrobble after restarting it.

**Comment by ilya-murzinov** [comment]
@lemerafael, yes, this is the same bug, but unfortunately we can't do anything about it, if player doesn't send track's duration. So it's actually only partially fixed :(
