### ISSUE TITLE
Widget to ''love" currently playing track on Last.FM

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#43]
Based on [this](https://play.google.com/store/apps/details?id=com.artemzin.android.wail&reviewId=Z3A6QU9xcFRPRXZ5RlpROE5kTGwxRmFwNTZRNVZMR2g2bS1PX3M4alh3eFhWYnhWTjFzeldvWFdrclJzZWN2Sm5pVTg0YVozc2ExX3hGRkxPMnBaV2RyRVE) review.

@artem-zinnatullin, do you want to have this feature?

**Comment by ilya-murzinov** [comment]
Done, closing.

**Comment by artem-zinnatullin** [comment]
Awesome
