### ISSUE TITLE
Add support for Rocket Player

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#58]

**Comment by dufferzafar** [comment]
:+1:

**Comment by dufferzafar** [comment]
Even though there is this file in the code, I tested out the v0.7.2 build and this does not work! https://github.com/artem-zinnatullin/android-wail-app/blob/39c8a7f18a44e20485e85382551cb9a8e8039fdf/wail-app/src/main/java/com/artemzin/android/wail/receiver/music/RocketMusicPlayerReceiver.java

I sadly have no knowledge of java :(

**Comment by lemerafael** [comment]
I checked the java class mentioned and I noticed something.
The package name "com.jrtstudio.music" is related to https://play.google.com/store/apps/details?id=com.jrtstudio.music&hl=en, not to Rocket Player. Rocket player has package name "com.jrtstudio.AnotherMusicPlayer" (link: https://play.google.com/store/apps/details?id=com.jrtstudio.AnotherMusicPlayer&hl=en)

I tried downloading the project on eclipse, but, as I am new to this, I got some errors and could not try it out... I wanted to help, maybe this is the answer? As it's a quick fix, could it be incorporated on the new version being released soon?

**Comment by dufferzafar** [comment]
@lemerafael Great find! Maybe this is it. Does someone who knows Android/Eclipse please help out?

**Comment by ilya-murzinov** [comment]
@lemerafael, nice!
I'll make this change today and then test it.

**Comment by ilya-murzinov** [comment]
Yep, that's it.
Now WAIL works with RocketPlayer, thanks to @lemerafael!

**Comment by lemerafael** [comment]
You are welcome!
