### ISSUE TITLE
Track doesn't scrobbles

### ISSUE THREAD

**Issue by keyursakaria** [artem-zinnatullin/android-wail-app#61]
Hi, 

In the track section where scrobbled tracks are shown there are some tracks which keeps showing scrobbling but doesn't gets scrobbled

**Comment by ilya-murzinov** [comment]
@keyursakaria, @tinosoft hi!
Is this bug still reproducible?

**Comment by ilya-murzinov** [comment]
No response in a half-a-year, closing this.
