### ISSUE TITLE
Turn off support for  Listen Audiobook Player

### ISSUE THREAD

**Issue by alehandrof** [artem-zinnatullin/android-wail-app#63]
Recently I noticed that WAIL was scrobbling from [Listen Audiobook Player](https://play.google.com/store/apps/details?id=com.acmeandroid.listen&hl=en). I don't really have any use for scrobbling audiobook tracks. Can you provide an option to turn off support for this player?

**Comment by ilya-murzinov** [comment]
I will add an option to ignore any player, see #76.
Closing this.

**Comment by alehandrof** [comment]
Sounds good. Thanks!
