### ISSUE TITLE
Ripple effect for buttons, FABs and touchable controls

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#72]

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, can you suggest a library for this?
I tried https://github.com/traex/RippleEffect, but didn't like it. For example, when after click new activity starts animation immediately stops and continues after returning to the original activity. Seems to be a bug to me.

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov unfortunately I don't know any good libraries for backporting ripple effect, I used ripple for Android L and standard selector with exitDuration for pre L

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, all right, I'll do the same.
