### ISSUE TITLE
Settings material design

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#81]
Settings screen needs to be redesigned.
I think, for start, just wrap settings categories in CardViews will be enough.

Part of #65

**Comment by artem-zinnatullin** [comment]
`CardView` for categories? Interesting, can you please post a screenshot

**Comment by ilya-murzinov** [comment]
Just look at settings in Android 5.

**Comment by artem-zinnatullin** [comment]
Oh, really :D Okay, LGTM

**Comment by ilya-murzinov** [comment]
This is how it's gonna look:
![screenshot_2015-01-19-14-17-28 1](https://cloud.githubusercontent.com/assets/3704363/5799672/2e648a1c-9fe6-11e4-9218-31a8404dd0c2.png)

**Comment by artem-zinnatullin** [comment]
Cool

**Comment by ilya-murzinov** [comment]
regroup settings items
