### ISSUE TITLE
Attach .apk to v0.7.0 release

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#87]
Draft was drafted in [releases](https://github.com/artem-zinnatullin/android-wail-app/releases)

**Comment by artem-zinnatullin** [comment]
Yo! Did you checked upgrade over current version in Google Play? I mean, DB upgrade, SharedPreferences and so on on live install over v0.6.5? Also, I think it's time to change "email developer" option and send it to not only mine email, but your too :)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, no, I didn't check. I'll do it now.
Does anybody use "email developer"? :)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov oh yes, sometimes I receive up to 3-4 emails per day, but in average -> about 4 emails per week, most of times I redirect users to GitHub issues or they just saying "Thanks!" last few months you deserved it much more than me :+1:

**Comment by ilya-murzinov** [comment]
Alright then, I'll add my email :)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, I tested updating app and added my e-mail.
Everything seems fine, I think we are ready to go! :)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov okay, lets do it!

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov done :+1:

**Comment by ilya-murzinov** [comment]
Great :)
