### ISSUE TITLE
Screenshots for Google Play and README

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#88]
Settings was redesigned + other Ui changes

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin I updated screenshots in README, are they ok now?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov LGTM, I'll use them for Google Play now

**Comment by artem-zinnatullin** [comment]
Done, closing
