### ISSUE TITLE
Error on Huawei MediaPad 10 fhd

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#89]
> Ошибка Вылетает сразу после запуска. Huawei MediaPad 10 fhd.

> Error immediately after launching app on Huawei MediaPad 10 fhd.

**Comment by ilya-murzinov** [comment]
F*ck.
@artem-zinnatullin, I tested on 4.0 emulator, what can be the problem?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov "Huawei" is the problem (it's a joke), I can't say anything without logs, Google Play crashlogs empty for v0.7.0, for v0.6.5 last and the only crash was on Sony Xperia phone

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, how can we ask him to send a report?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov I forgot about Google Analytics! Here is the crash for v0.7.0, but it could be from debug version: `NullPointerException (@MainFragment:onCreate:195) {main}`

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov may be you forget to change layouts for Tablets? (Just thinking)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin I'll check it

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, that's right, forgot about landscape layout, fixing it.

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov okay, I got same bug on Nexus 7 after rotating to landscape, ping me when you'll prepare v0.7.1 with bugfix, I'll publish it ASAP

**Comment by ilya-murzinov** [comment]
Fixed.

**Comment by ilya-murzinov** [comment]
> Александр Нефедов  20 января 2015 г.
> Фурычит Красавец

:))))))

**Comment by artem-zinnatullin** [comment]
![screen shot 2015-01-20 at 18 40 41](https://cloud.githubusercontent.com/assets/967132/5820286/03e38a5a-a0d5-11e4-8931-4880324519cf.png)

"Апполон" :D
