### ISSUE TITLE
Prepare new release

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#91]
Fixed both bugs, #89 and #90, app needs to be updated in Google Play ASAP.
Really sorry for this :(

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov okay, publishing, hope fix for #90 won't brake anything

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, it should not, it's quite clear in my opinion..

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov done, waiting for angry users :)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, I certainly hope there will not be lots of them :)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov sure, most of users does not check Google Play updates manually, Google Play usually installs auto-updates at night or in the morning, for many users v0.7.1 will be available at this moment
