### ISSUE TITLE
Landscape mode Ui Navigation Drawer item is not selected by default

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/android-wail-app#94]
Nexus 7, landscape mode

1) Launch the app
2) Main fragment selected by default
3) "Main" is not selected in Navigation Drawer

![2015-01-20 16 17 24](https://cloud.githubusercontent.com/assets/967132/5820894/4944d58c-a0d9-11e4-805a-d325f4234d7a.png)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin nice idea to test app on tablet after release :))))

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov  "Huyak huyak & to production!" Tablets!
