### ISSUE TITLE
New nav. drawer

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#95]
Thanks to [this](https://play.google.com/store/apps/details?id=com.artemzin.android.wail&reviewId=Z3A6QU9xcFRPR2Nab3ljdnBOZ2VyTFhUMW1namdFazNocGFyR1FRWXlJQm9sWmtGSzdUYkx3SE5hTmpQX0hUYzlOWkZEb2tRaVVyNG9WVG9yN2kxWHFPcnc) review on Google Play.

>Последнее обновление вообще шикарно, но гайдлайны автору все же лучше перечитать :) Иконка поиска и боковое меню не вписываются.

Guidelines: [navigation drawer](http://www.google.com/design/spec/patterns/navigation-drawer.html)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, drawer not finished but idea is:
![screenshot_2015-01-21-21-00-32](https://cloud.githubusercontent.com/assets/3704363/5841791/b0ea8b32-a1b0-11e4-8282-d317f86348ca.png)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov cool, also will be great to add some image into drawer, like
Pushbullet, or Gmail, or Google Play

ср, 21 янв. 2015, 21:02, Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, I updated preview above.
Any idea what kind of picture can we use in background?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov can you please check Public Licence of standard Lolipop wallpapers? if it's okay, you can put one of them into Nav Drawer, also, would be better if Nav Drawer will be under status bar on Lolipop (see apps I mentioned earlier)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, is landscape layout ok? I tested om Nexus 5, not tablet of course.
![screenshot_2015-01-22-18-16-48](https://cloud.githubusercontent.com/assets/3704363/5858301/111a9062-a263-11e4-8239-ec1d1dd5b52b.png)
![screenshot_2015-01-22-18-16-52](https://cloud.githubusercontent.com/assets/3704363/5858302/11251eba-a263-11e4-8b9a-b2fccb81c5c1.png)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov I'll be able to test in several hours, if you want to do it yourself, I'd recommend to use Genymotion they have Nexus 7, Nexus 10 configurations of emulators, Genymotion emulators are great

**Comment by ilya-murzinov** [comment]
It's still not ready for testing, I just wonder if you like how it looks.

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov Ui LGTM, icons, user info, Navigation Drawer hipster pack for Android App :+1:

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin should we highlight current item in drawer? I can't decide :)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov yes, of course, check several apps and decide how to do it :)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, almost final version:
![screenshot_2015-01-23-16-10-41](https://cloud.githubusercontent.com/assets/3704363/5875122/aa063c24-a31a-11e4-927b-b105ddabf56a.png)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov cool, let's publish it :+1:
