### ISSUE TITLE
Opening some other apps causes Wail Beta to open instead

### ISSUE THREAD

**Issue by Pichu0102** [artem-zinnatullin/android-wail-app#96]
Two apps I've noticed; SimplyNoise and Text Sizer for Dolphin; have an issue where after the Wail update, you can't open them without Wail opening and taking over. The only way to stop this behavior is to disable or uninstall Wail from the OS' app information menu.

**Comment by ilya-murzinov** [comment]
@Pichu0102, hello!
I've fixed this bug in **v0.7.1**, make sure you update the app to latest version.
See #90
