### ISSUE TITLE
New launcher icon

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#98]
see #95
Guidelines: [icons](http://www.google.com/design/spec/style/icons.html#icons-system-icons)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin can you help with this?)
I'm not an expert, but I think the current icon is not "material".
Is there any chance you can draw a new one? Or may be you think it's not necessary?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov the problem is that I agree, "icon is not material", but I am not a designer to draw new one :(

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin didn't you draw original one? If not, who did? Can't he/she draw a new one?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov I found it on one of the "Icons stocks" with free licence (I hope)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, ok then, I'll move it to next version.

**Comment by Stebo91** [comment]
![wailbetamd](https://cloud.githubusercontent.com/assets/3914326/6671620/d9b8b9fa-cc06-11e4-8aa4-fe9885aaf1cb.png)

what do you think about this one?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov take a look! 

I love the idea, @ilya-murzinov can you please make screenshot from launcher? I am very busy with work :disappointed: 

Or I'll take screenshot tonight

@Stebo91 great work! Where are you doing it: Sketch, Illustrator, Photoshop?

**Comment by Stebo91** [comment]
Thank you @artem-zinnatullin ! I just used Photoshop

**Comment by artem-zinnatullin** [comment]
Here are the screenshots:

1.
![1](https://cloud.githubusercontent.com/assets/967132/6677988/14de820a-cc46-11e4-8f54-9b5e69ae483c.png)

2.
![2](https://cloud.githubusercontent.com/assets/967132/6677991/20c6857c-cc46-11e4-91b6-aa2770b11ce8.png)

3.
![3](https://cloud.githubusercontent.com/assets/967132/6677993/275eaae0-cc46-11e4-8660-abb5cbad5ea0.png)

4.
![4](https://cloud.githubusercontent.com/assets/967132/6677994/2c9a1620-cc46-11e4-8c53-3c755d948675.png)


I love 2nd, shadows are really `Material`.

@ilya-murzinov what do you think?

@Stebo91 which would you prefer?

**Comment by Stebo91** [comment]
@artem-zinnatullin I'd say 1 or 2

**Comment by ilya-murzinov** [comment]
@Stebo91, great job!
I really like all the icons (especially, №4 for some reason :) ).
But I think the main color has to be blue, because the main color in the application is blue.
@artem-zinnatullin, do you agree?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov LOL

We can change current blue color to this one from icon :)

№4 breaks the idea of "Vinyl Record with synchronization" because it's square

**Comment by Stebo91** [comment]
![wailbetamd5](https://cloud.githubusercontent.com/assets/3914326/6685363/6b299818-cc99-11e4-9386-c56680c18abd.png) ![wailbetamd6](https://cloud.githubusercontent.com/assets/3914326/6685362/6b24d594-cc99-11e4-83eb-2e47a207063c.png) ![wailbetamd7](https://cloud.githubusercontent.com/assets/3914326/6685365/6b3327a2-cc99-11e4-813f-a4869853e603.png) ![wailbetamd8](https://cloud.githubusercontent.com/assets/3914326/6685364/6b2e1208-cc99-11e4-8c4b-fc97ce80ab61.png)

@ilya-murzinov @artem-zinnatullin 
Here are some blue versions (although I think blue is kind of overused in icons nowadays).

**Comment by artem-zinnatullin** [comment]
@Stebo91 nice colors!

But I'd agree about overuse of blue color, just opened launcher: 22 of 61 icons are blue

**Comment by Stebo91** [comment]
@artem-zinnatullin  Thanks!!! anyways if you guys can think about any other combination of colors, just let me know and I'll do it :)

**Comment by Stebo91** [comment]
![wailbetamd9](https://cloud.githubusercontent.com/assets/3914326/6686037/3f8b123a-cc9f-11e4-8ca0-61f6fbc5888c.png) ![wailbetamd10](https://cloud.githubusercontent.com/assets/3914326/6686038/3f90c8f6-cc9f-11e4-843f-94a45d2d385a.png)

These two are inspired by Google Play Music. I personally like a lot these colors

**Comment by Stebo91** [comment]
@artem-zinnatullin @ilya-murzinov  have you decided yet? I'm curious :)

**Comment by artem-zinnatullin** [comment]
@Stebo91 @ilya-murzinov I am sorry, I had exams in my University on previous week and now I have to write diploma..

Just select one of the great icons and I'll try to publish new build on Google Play

**Comment by Stebo91** [comment]
![e04a6c94-cc0d-11e4-8167-14ecf207408c](https://cloud.githubusercontent.com/assets/3914326/7042415/02e9d790-dde2-11e4-8fb9-3e88b56280cf.png) ![3f90c8f6-cc9f-11e4-843f-94a45d2d385a](https://cloud.githubusercontent.com/assets/3914326/7042417/03facd74-dde2-11e4-921c-0a0db1516bc8.png)

@artem-zinnatullin  @ilya-murzinov  Personally #2 is my favorite, but probably #1 is more consistent with the app UI.

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov your opinion?

I'd prefer #1 from last comment

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, @Stebo91 I presonally like orange+black, but I'm OK with #1 :)

**Comment by ilya-murzinov** [comment]
@Stebo91, sorry for the delay :)
Can you please submit a PR with this one?
![image](https://cloud.githubusercontent.com/assets/3704363/8025355/18044080-0d5c-11e5-9880-1eb0745a4df1.png)

**Comment by Stebo91** [comment]
Uhm...how?

**Comment by ilya-murzinov** [comment]
@Stebo91 have you ever worked with Android and/or git? :)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov I think you can add icon to the app :)

**Comment by ilya-murzinov** [comment]
@Stebo91, yeah, I can, but I thought maybe @Stebo91 wants to do it himself :)

**Comment by ilya-murzinov** [comment]
And also, the quality of the picture after uploading it to GitHub is inappropriate :(

**Comment by Stebo91** [comment]
Not really, no xD

**Comment by ilya-murzinov** [comment]
@Stebo91, @artem-zinnatullin alright then, I'll do it :)
Can  you please send me hi-quality version of the image to murz42@gmail.com ?

**Comment by Stebo91** [comment]
ok!

2015-06-07 22:11 GMT+02:00 Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
I asked @Stebo91 also to create an icon for the notification.
@Stebo91, please post your version here so we could decide :)

**Comment by Stebo91** [comment]
these days I'm kind of busy, I'll try to make a nice one on Thursday :)

2015-06-11 11:38 GMT+02:00 Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
@Stebo91, no rush :)

**Comment by Stebo91** [comment]
Ok this is what I did (I posted it in black otherwise you wouldn't see it).
I attach also the white version in the different dimensions :)

[image: Immagine in linea 1]

2015-06-15 23:01 GMT+02:00 Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
@Stebo91, thank you, it's very nice!
It's white, so no discussion about the color here :)
